### ISSUE TITLE
could you please tag new releases

### ISSUE THREAD

**Issue by palica** [057a3dd61f99517a3afea0051a49cb27994f94d/rslinux#2]
this helps to install them from source.tar.gz not having to search in git log. thanks

**Comment by 057a3dd61f99517a3afea0051a49cb27994f94d** [comment]
Sure.

**Comment by palica** [comment]
Thank you.

works now just fine :)

e.g.:
https://github.com/057a3dd61f99517a3afea0051a49cb27994f94d/rslinux/archive/rs-v2.1.2.tar.gz
